# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

point_in_polygon <- function(point, polygon, boundary = TRUE) {
    .Call(`_GMMBasketShotCharts_point_in_polygon`, point, polygon, boundary)
}

